version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
      - database
    ports:
      - "8000:80"
    networks:
      - php-stack

  php-fpm:
    build:
      args:
        user: teddi
        uid: 1000
      context: ./php-fpm
    container_name: php-fpm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app/:/var/www/
      - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database
    networks:
      - php-stack

  database:
    image: mariadb:latest
    container_name: database
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - ./database/mysql_data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - php-stack

networks:
  php-stack:
    name: php-stack
    driver: bridge